
isy_host: 192.168.1.64
isy_port: 80
isy_user: admin
isy_password: notmypassword

router_type: asus
# test host
#router_host: 190.53.26.252
router_host: 192.168.1.1
router_user: admin
router_password: notmypassword

log_file: pylink.log
